version: '3.8'

services:
  db:
    restart: on-failure
    image: postgres:16-alpine
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mentorship-dev
    ports:
      - '5432:5432'

  server:
    restart: unless-stopped
    depends_on:
      - db
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_URL=postgresql://postgres:password@db:5432/mentorship-dev
    ports:
      - '3000:3000'

volumes:
  postgres-data:
