version: '3.8'

services:
  db:
    ports:
      - '5432:5432'
    volumes:
      - ./docker/db_scripts:/docker-entrypoint-initdb.d/
  server:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - /code/node_modules
      - ./:/code
    environment:
      - DB_HOST=db
      - DB_PORT=5432
    ports:
      - '3000:3000'
