version: '3.8'

services:
  db:
    restart: on-failure
    image: postgres:16-alpine
    environment:
      - POSTGRES_PASSWORD=password
  server:
    restart: unless-stopped
    depends_on:
      - db
    build:
      context: ./
      dockerfile: Dockerfile
