name: Build & Deploy

on:
  push:
    paths:
      - server/**
      - .github/**
    branches:
      - master

jobs:
  docker:
    name: Docker Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Docker BuildX
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: server
          tags: ahmedsadman/mentorship-server:latest

  deploy:
    name: Deploy
    needs: docker
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Deploy
        run: curl ${{ secrets.DEPLOY_WEBHOOK }}

      - name: Wait
        run: sleep 30

      - name: Healthcheck
        run: curl --max-time 60 ${{ secrets.HEALTHCHECK_URL }}
