name: Build And Deploy

on:
  push:


jobs:
  docker-push:
    name: Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Docker BuildX
        run: echo Hi

