name: PR Status (Server)

on:
  pull_request:
    paths:
      - server/**
    branches:
      - master

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Tests
        run: |
          echo --- Running Test Suite ---
          ./scripts.sh test_server
          echo --- Test Suite Complete ---
